### Objective- Performing Naive Bayes Classification on the titanic dataset.

In [1]:
#Importing all necessary library
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline


C:\Users\DELL\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [13]:
dataset=pd.read_csv("Titanic_train.csv")
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [14]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

Can be seen that **Cabin** has more than **80%** of the null value. Hence can be dropped along with **PassengerId, Name, Ticket**

In [15]:
#Dropping the columns
dataset=dataset.drop(['Cabin','PassengerId','Ticket','Name'],axis=1)
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [16]:
#Variable Sex and Embarked can be concerted to numeric type
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Sex"]=le.fit_transform(dataset["Sex"])
dataset["Embarked"]=le.fit_transform(dataset["Embarked"])
dataset.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [17]:
dataset.shape

(889, 8)

In [10]:
#Doing the train_test_split
from sklearn.model_selection import train_test_split



In [12]:
#importing library for classification
from sklearn.naive_bayes import *
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

### 1. Survival Classification

In [21]:

y = dataset['Survived']
X = dataset.drop(['Survived'],axis=1)
#Splitting data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
ypred = clf.fit(X_train,y_train).predict(X_test)
ypred
#Model accuracy
print("Accuracy :", accuracy_score(y_test,ypred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y_test,ypred))

Accuracy : 0.8202247191011236
Confusion matrix :
 [[143  23]
 [ 25  76]]


### 2. PClass Classification

In [28]:
y2 = dataset['Pclass']
X2 = dataset.drop(['Pclass'],axis=1)
#Splitting data
X2_train,X2_test,y2_train,y2_test = train_test_split(X2,y2,test_size=0.3,random_state=5)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y2pred = clf.fit(X2_train,y2_train).predict(X2_test)
y2pred
#Model accuracy
print("Accuracy :", accuracy_score(y2_test,y2pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y2_test,y2pred))

Accuracy : 0.599250936329588
Confusion matrix :
 [[ 22   1  40]
 [ 13   2  42]
 [  9   2 136]]


### 3. Sex Clasification

In [33]:
y3 = dataset['Sex']
X3 = dataset.drop(['Sex'],axis=1)
#Splitting data
X3_train,X3_test,y3_train,y3_test = train_test_split(X3,y3,test_size=0.3,random_state=5)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y3pred = clf.fit(X3_train,y3_train).predict(X3_test)
y3pred
#Model accuracy
print("Accuracy :", accuracy_score(y3_test,y3pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y3_test,y3pred))

Accuracy : 0.8202247191011236
Confusion matrix :
 [[ 66  16]
 [ 32 153]]


### 4. SibSp Classification

In [39]:
y4 = dataset['SibSp']
X4 = dataset.drop(['SibSp'],axis=1)
#Splitting data
X4_train,X4_test,y4_train,y4_test = train_test_split(X4,y4,test_size=0.3,random_state=5)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y4pred = clf.fit(X4_train,y4_train).predict(X4_test)
y4pred
#Model accuracy
print("Accuracy :", accuracy_score(y4_test,y4pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y4_test,y4pred))

Accuracy : 0.6966292134831461
Confusion matrix :
 [[169  14   0   0   0   0   0]
 [ 46  17   0   0   0   0   0]
 [  6   3   0   0   0   0   0]
 [  2   2   0   0   0   0   0]
 [  3   0   0   0   0   0   0]
 [  3   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0]]


### 5. Parch Classification

In [42]:
y5 = dataset['Parch']
X5 = dataset.drop(['Parch'],axis=1)
#Splitting data
X5_train,X5_test,y5_train,y5_test = train_test_split(X5,y5,test_size=0.3,random_state=5)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y5pred = clf.fit(X5_train,y5_train).predict(X5_test)
y5pred
#Model accuracy
print("Accuracy :", accuracy_score(y5_test,y5pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y5_test,y5pred))

Accuracy : 0.7565543071161048
Confusion matrix :
 [[194  17   0   0   0]
 [ 31   8   0   0   0]
 [ 11   4   0   0   0]
 [  0   1   0   0   0]
 [  1   0   0   0   0]]


### 6. Embarked Classification

In [51]:
y6 = dataset['Embarked']
X6 = dataset.drop(['Embarked'],axis=1)
#Splitting data
X6_train,X6_test,y6_train,y6_test = train_test_split(X6,y6,test_size=0.3,random_state=15)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y6pred = clf.fit(X6_train,y6_train).predict(X6_test)
y6pred
#Model accuracy
print("Accuracy :", accuracy_score(y6_test,y6pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y6_test,y6pred))

Accuracy : 0.7528089887640449
Confusion matrix :
 [[  0   0  48]
 [  0   0  18]
 [  0   0 201]]
