# Numpy programming


## 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

a = np.random.random((3,3,3))
print(a)

[[[0.62948552 0.93840288 0.71727662]
  [0.29412767 0.25480205 0.14676034]
  [0.09197212 0.39094884 0.95852088]]

 [[0.17958457 0.35693619 0.53363205]
  [0.41989498 0.52868257 0.06302834]
  [0.74777391 0.24734991 0.03118013]]

 [[0.61740465 0.97962004 0.15920237]
  [0.78245288 0.97522361 0.25373628]
  [0.83379231 0.57212154 0.50704711]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
b = np.diag(1+np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
c = np.zeros((8,8),dtype=int)
c[1::2,::2] = 1
c[::2,1::2] = 1
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.50795741  1.08281797 -1.13080524  0.44485915  0.18972331]
 [ 1.45195912 -0.16190807 -0.29876209 -1.4540887   1.06244091]
 [-0.94034821  1.55882615 -1.01013745 -0.51080876 -1.38998606]
 [-1.29964623 -0.23950449 -1.14703193 -0.78469363  1.71505872]
 [ 1.01103262 -0.44702322  0.31010888  1.45757242  0.02238741]]


# 5. How to find common values between two arrays?

In [5]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-01
2020-08-02
2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [7]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.18433978 0.18913472 0.61896455 0.09706681 0.69693018 0.29318247
 0.34672483 0.63600927 0.23960756 0.        ]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-0.12528541  0.1373785  -0.0323592   0.3146502  -0.04336567 -0.22396496
  -0.21228427  0.3069226   0.39994987 -0.52164166]
 [ 0.32614115  0.09126418  0.27897034 -0.42417461  0.2126012  -0.26304564
   0.16643084 -0.00642198  0.06947489 -0.45124038]
 [-0.15610628  0.02264544  0.14742364  0.04337364  0.3310955  -0.43611573
   0.40083447 -0.36642082  0.16459465 -0.15132451]
 [-0.17525562  0.35973438  0.03230641  0.16120227 -0.35284438 -0.14394373
  -0.11726306  0.08420459  0.16829155 -0.0164324 ]
 [-0.12246931  0.03799588 -0.0146728   0.14093804 -0.45552345  0.03093724
   0.00631798 -0.07359418  0.22609525  0.22397537]]
[[-0.12528541  0.1373785  -0.0323592   0.3146502  -0.04336567 -0.22396496
  -0.21228427  0.3069226   0.39994987 -0.52164166]
 [ 0.32614115  0.09126418  0.27897034 -0.42417461  0.2126012  -0.26304564
   0.16643084 -0.00642198  0.06947489 -0.45124038]
 [-0.15610628  0.02264544  0.14742364  0.04337364  0.3310955  -0.43611573
   0.40083447 -0.36642082  0.16459465 -0.15132451]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 1. 4. 2. 4. 1. 3. 2. 7. 3.]
[ 5.  1.  7.  3.  7.  1.  5.  3. 13.  5.]


# 12.How to get the diagonal of a dot product?

In [14]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.40760714 0.75914655 0.91276773]
 [0.7627755  0.8985706  0.51510846]
 [0.04987417 0.41748736 0.8627379 ]]
[[0.82958122 0.9599485  0.31314071]
 [0.33017073 0.60910086 0.71653849]
 [0.70205783 0.93523027 0.4667918 ]]
diagonal of a dot product method 1 is.... [1.22960693 1.76129035 0.71748237]
diagonal of a dot product method 2 is.... [1.22960693 1.76129035 0.71748237]


# 13.How to find the most frequent value in an array?


In [15]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[1 8 9 0 0 3 7 8 2 2 8 0 2 2 4 1 9 7 9 9 2 8 2 1 6 5 3 3 3 5 3 6 0 0 6 8 5
 0 7 2 7 5 2 3 4 7 7 4 9 7]
2


# 14.How to get the n largest values of an array

In [16]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [17]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
